INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'Kimi no Na Wa.', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Violet Evergarden Gaiden: Eien to Jidou Shuki Ningyou', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/tRvNnYnqxJMqQu8ByIUea3bGSRY.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Koe no Katachi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Tenki no Ko', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wRDyTXw5j0RN9M03xZlHYkoNLCI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Josee to Tora to Sakana-tachi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/bynLqvsyEEicIE3KNKUiDEy3X39.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sen to Chihiro no Kamikakushi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Tonari no Totoro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fxYazFVeOCHpHwuqGuiqcCTw162.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Majo no Takkyuubin', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/h5pAEVma835u8xoE60kmLVopLct.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sayonara no Asa ni Yakusoku no Hana wo Kazarou', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/pSsHFCwM5KMoRCc8X8wjpUDrlvr.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kimi no Suizou wo Tabetai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/BNzgGEl0DQiQTPyPcIfcuner1Q.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Uchiage Hanabi, Shita kara Miru ka? Yoko kara Miru ka?', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fspXD0mRE4mLPx4dpBP2VUHTflj.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shikioriori', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cMr9E86SJhIrIdfD0ctUnNwoDVw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cider no You ni Kotoba ga Wakiagaru', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/bmQo9jJqbfEWfg3nHUSR5bBxDxA.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Omoide Poroporo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hqhsZX2VKvi4UZ9uDyn9eCEGQmv.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Birthday Wonderland', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vawafIW1ONZTONAoZcb6pvWoPe6.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Nakitai Watashi wa Neko wo Kaburu', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eHTZoXmB4vnDqANZXPZcdAiYQo5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Suki ni Naru Sono Shunkan wo.: Kokuhaku Jikkou Iinkai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lTbYegQ35QRWlWvDqYwS0okFiY4.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Zutto Mae kara Suki deshita.: Kokuhaku Jikkou Iinkai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/zyqfXxJVhPOTIKHDeFBQXx1IIXl.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Love Live! The School Idol Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mQyRY4ueFsSPYpcWoj5qgz5JzSl.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Love Live! Sunshine!! The School Idol Movie: Over the Rainbow', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uzUBk8g0jm4CzuvzRYjLORREZzw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'K-On! Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/ydhtzzLouUZsMSnCiswAkaPQrB6.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Toki wo Kakeru Shoujo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/iu1Xxh86uRX7b5r0NpBv7qYRqBW.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Ookami Kodomo no Ame to Yuki', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eNWjMbuhGxJdzaIY9ZZ2KvWx2sQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kono Sekai no Katasumi ni', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mNOB5JoW1imvdGrZ52RGZgJCop0.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kokoro ga Sakebitagatterunda', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kfGUVDM03SGHIV1e3oS7R68j8Ek.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Byousoku 5 Centimeter', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7Ly4Smxxp5qBBxsoIZ4otEOG1kc.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shoujo☆Kageki Revue Starlight Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/bJZpSHArR8HJL6ncnjDKd4r2tpN.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Summer Wars', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wSFAoevZuVBo4L9f8NgYSD1o9cQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kaguya-hime no Monogatari', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/imUJOrtNf8EWameChpaRLXSaX4w.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Yuru Yuri Nachuyachumi!', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wNETLi299nbNLlAEUozPGc8AeM5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'BLACKFOX', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8sy0d7k7zRXWlydi5TvvGpraNKe.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Gake no Ue no Ponyo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/efZ10EscERir1yU60KsSjLNa6ZJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Giniro no Kami no Agito', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/dS1rOjnhgqTbEebLLAIQ7tG7hyB.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Hakubo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mAaKxURFBRkLVfpqKOFVND78F13.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Hibike! Euphonium Movie 1: Kitauji Koukou Suisougaku-bu e Youkoso', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wMuXTor7cw9XZQQeJLXSvOfCEkF.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Hibike! Euphonium Movie 2: Todoketai Melody', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kH2nsjFGLKrBqjpv3VsnRJVFMH5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Hibike! Euphonium Movie 3: Chikai no Finale', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uRBxFxB0wlYfsaF6Pf8DeEEAq4V.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Howl no Ugoku Shiro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vwBa7djy1oxfxUjc7YtVgGNsjrT.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kimi no Koe wo Todoketai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6nKcYUEIFSbWRymT7BV1nD197Gx.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kotonoha no Niwa', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6ljxY3k2Or1iEpjwBlrAuaGUIlK.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Koukaku Kidoutai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/g0pF9jXhPqm6TN3AAMWn0YeYayi.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Liz to Aoi Tori', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mG3CYBXgCPi0yYHSygKNtqGpEkd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Mirai no Mirai', 'https://www.themoviedb.org/t/p/w533_and_h300_face/1TSGVVap3ONYMk0G1uLDwcVzv8d.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Neko no Ongaeshi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cuiJ6e6kSatyRlnCJrvJG2ElpSg.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Non Non Biyori Movie: Vacation', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/xv9mCcrT3GAvk4IhbdaXxv4ylqt.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shoujo☆Kageki Revue Starlight: Rondo Rondo Rondo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9I86MnJ6POxgxC4YvEVrtXxMv1x.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Tenkuu no Shiro Laputa', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/3cyjYtLWCBE1uvWINHFsFnE8LUK.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Violet Evergarden Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/zBvR0lJyKH37FPQTj5mFfYr2X4s.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wIeNWRuBCdEBmWoDRcKputYV414.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Suzumiya Haruhi no Shoushitsu', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/AhHQFrbtA6AkWjefpIKMOd7Dzpe.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Fragtime', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/w8mUnylYIkKfwzCIeyxXSQt055N.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kimi to, Nami ni Noretara', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vooRKLGVvFRFmx9swcMh26uYZSf.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Saenai Heroine no Sodatekata Fine', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/1DbWrFIn8BJpmNx2eSUomtLPhPH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sora no Aosa wo Shiru Hito yo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/k1jWHgAICsNGM5roYcIwaDpryYS.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Given Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Tamako Love Story', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6Nz34wS45PsHUpk1SPBjFGzbCBZ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Ai no Utagoe wo Kikasete', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4nswAImPQjLbyCpXkwHjFlXxAeG.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Summer Ghost', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kjCJ8L5JzpF5WqBdFSwHeuW37DH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kakushigoto Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/evm4KLYl7c5wXsnbMPTkLnq7RtN.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Omoi, Omoware, Furi, Furare', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/DRn1kuSWB1fd3k3l1VufX2dFqV.jpg');


INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);