INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'Kimi no Na Wa.', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Violet Evergarden Gaiden: Eien to Jidou Shuki Ningyou', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/tRvNnYnqxJMqQu8ByIUea3bGSRY.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Koe no Katachi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Tenki no Ko', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wRDyTXw5j0RN9M03xZlHYkoNLCI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Josee to Tora to Sakana-tachi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/bynLqvsyEEicIE3KNKUiDEy3X39.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sen to Chihiro no Kamikakushi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Tonari no Totoro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fxYazFVeOCHpHwuqGuiqcCTw162.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Majo no Takkyuubin', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/h5pAEVma835u8xoE60kmLVopLct.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sayonara no Asa ni Yakusoku no Hana wo Kazarou', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/pSsHFCwM5KMoRCc8X8wjpUDrlvr.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kimi no Suizou wo Tabetai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/BNzgGEl0DQiQTPyPcIfcuner1Q.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Uchiage Hanabi, Shita kara Miru ka? Yoko kara Miru ka?', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fspXD0mRE4mLPx4dpBP2VUHTflj.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shikioriori', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cMr9E86SJhIrIdfD0ctUnNwoDVw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cider no You ni Kotoba ga Wakiagaru', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/bmQo9jJqbfEWfg3nHUSR5bBxDxA.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Omoide Poroporo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hqhsZX2VKvi4UZ9uDyn9eCEGQmv.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Birthday Wonderland', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vawafIW1ONZTONAoZcb6pvWoPe6.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Nakitai Watashi wa Neko wo Kaburu', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eHTZoXmB4vnDqANZXPZcdAiYQo5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Suki ni Naru Sono Shunkan wo.: Kokuhaku Jikkou Iinkai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lTbYegQ35QRWlWvDqYwS0okFiY4.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Zutto Mae kara Suki deshita.: Kokuhaku Jikkou Iinkai', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/zyqfXxJVhPOTIKHDeFBQXx1IIXl.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Love Live! The School Idol Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mQyRY4ueFsSPYpcWoj5qgz5JzSl.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Love Live! Sunshine!! The School Idol Movie: Over the Rainbow', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uzUBk8g0jm4CzuvzRYjLORREZzw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'K-On! Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/ydhtzzLouUZsMSnCiswAkaPQrB6.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Toki wo Kakeru Shoujo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/iu1Xxh86uRX7b5r0NpBv7qYRqBW.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Ookami Kodomo no Ame to Yuki', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eNWjMbuhGxJdzaIY9ZZ2KvWx2sQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kono Sekai no Katasumi ni', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mNOB5JoW1imvdGrZ52RGZgJCop0.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kokoro ga Sakebitagatterunda', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kfGUVDM03SGHIV1e3oS7R68j8Ek.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Byousoku 5 Centimeter', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7Ly4Smxxp5qBBxsoIZ4otEOG1kc.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shoujo☆Kageki Revue Starlight Movie', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/bJZpSHArR8HJL6ncnjDKd4r2tpN.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Summer Wars', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wSFAoevZuVBo4L9f8NgYSD1o9cQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Kaguya-hime no Monogatari', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/imUJOrtNf8EWameChpaRLXSaX4w.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Yuru Yuri Nachuyachumi!', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wNETLi299nbNLlAEUozPGc8AeM5.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);